# -*- coding: utf-8 -*-
"""Copy of TELEGRAM BOT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJNKtdhKggTi4zKz507DpSmpaadRgLyf
"""

#AIMER Society - Indian Servers
!pip install pyTelegramBotAPI
!pip install openai
!pip install google-generativeai #For Google Gemini #AIMERS
!pip install anthropic
TelegramBOT_TOKEN = '7243907591:AAGPdLJyUxy8ktR53jAO7CO-D-ZmGF7ZdLo'

#Latest version
import telebot
import os
import openai
from openai import OpenAI


OPENAI_API_KEY = "sk-proj-AlRYXo3Gr2OBdZIeNp3lT3BlbkFJqjvgQNcpEXOyVMK7KAzz"
client = OpenAI(api_key=OPENAI_API_KEY)


bot = telebot.TeleBot(TelegramBOT_TOKEN)

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, "Welcome! The MOST POWERFUL AI BOT")

@bot.message_handler(func=lambda message: True)
def handle_message(message):
 try :
  print(message)
  completion = client.chat.completions.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "user", "content": message.text},
  ]
    )
  bot.reply_to(message, completion.choices[0].message.content)
 except Exception as e:
        print(f"An error occurred: {e}")
        bot.reply_to(message, "Sorry, I couldn't process your request.")

bot.polling()